# Generated by Django 6.0.6 on 2026-08-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
